### ISSUE TITLE
Tried to run client to test for issues before pushing to server and had an error. I can't make heads or tails of the crash report.

### ISSUE THREAD

**Issue by AkuaTsubasa** [IminhaK/Excavation#36]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2022-10-05 22:32:52
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.1.33-universal.jar%23200!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.1.33-universal.jar%23200!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:604) ~[client-1.19.2-20220805.130853-srg.jar%23195!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.19.2-20220805.130853-srg.jar%23195!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1290) ~[client-1.19.2-20220805.130853-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23195!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23195!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.33.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD excavation --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.33.jar%23197!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.33.jar%23196!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ColorHandlerEvent$Block
		at bloop.excavation.Excavation.clientStart(Excavation.java:35) ~[excavation-1.19-1.8.jar%23165!/:1.19-1.8] {re:classloading}
		at bloop.excavation.Excavation.lambda$new$0(Excavation.java:29) ~[excavation-1.19-1.8.jar%23165!/:1.19-1.8] {re:classloading}
		at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19.2-43.1.33.jar%23196!/:?] {}
		at net.minecraftforge.fml.DistExecutor.runWhenOn(DistExecutor.java:95) ~[fmlcore-1.19.2-43.1.33.jar%23196!/:?] {}
		at bloop.excavation.Excavation.<init>(Excavation.java:29) ~[excavation-1.19-1.8.jar%23165!/:1.19-1.8] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.33.jar%23197!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.33.jar%23196!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/bluem/AppData/Roaming/.minecraft/mods/excavation-1.19-1.8.jar
	Failure message: Excavation (excavation) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.19-1.8
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.event.ColorHandlerEvent$Block
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at bloop.excavation.Excavation.clientStart(Excavation.java:35) ~[excavation-1.19-1.8.jar%23165!/:1.19-1.8] {re:classloading}
	at bloop.excavation.Excavation.lambda$new$0(Excavation.java:29) ~[excavation-1.19-1.8.jar%23165!/:1.19-1.8] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19.2-43.1.33.jar%23196!/:?] {}
	at net.minecraftforge.fml.DistExecutor.runWhenOn(DistExecutor.java:95) ~[fmlcore-1.19.2-43.1.33.jar%23196!/:?] {}
	at bloop.excavation.Excavation.<init>(Excavation.java:29) ~[excavation-1.19-1.8.jar%23165!/:1.19-1.8] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.33.jar%23197!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.33.jar%23196!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 584902880 bytes (557 MiB) / 973078528 bytes (928 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 970
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x13c2
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1259
	Graphics card #1 name: Intel(R) HD Graphics 4000
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 2112.00
	Graphics card #1 deviceId: 0x0162
	Graphics card #1 versionInfo: DriverVersion=10.18.10.4252
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.87
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.87
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 28043.38
	Virtual memory used (MB): 14572.28
	Swap memory total (MB): 11776.00
	Swap memory used (MB): 479.82
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.19.2_HD_U_H9
	OptiFine Build: 20220820-230904
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 512.59
	OpenGlRenderer: NVIDIA GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.1.33.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.33.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.1.33.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.1.33.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.33.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		elytraslot-forge-6.0.0+1.19.2.jar                 |Elytra Slot                   |elytraslot                    |6.0.0+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		netherportalfix-forge-1.19-10.0.0.jar             |NetherPortalFix               |netherportalfix               |10.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedstorage-1.19.2-0.5.18.151.jar        |Sophisticated Storage         |sophisticatedstorage          |1.19.2-0.5.18.151   |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.3.0.262.jar                   |Just Enough Items             |jei                           |11.3.0.262          |COMMON_SET|Manifest: NOSIGNATURE
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedcore-1.19.2-0.5.12.130.jar           |Sophisticated Core            |sophisticatedcore             |1.19.2-0.5.12.130   |COMMON_SET|Manifest: NOSIGNATURE
		excavation-1.19-1.8.jar                           |Excavation                    |excavation                    |1.19-1.8            |ERROR     |Manifest: NOSIGNATURE
		waystones-forge-1.19-11.1.0.jar                   |Waystones                     |waystones                     |11.1.0              |COMMON_SET|Manifest: NOSIGNATURE
		ForgeEndertech-1.19.2-10.0.5.0-build.0599.jar     |ForgeEndertech                |forgeendertech                |10.0.5.0            |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.19.2-9.0.0+11.jar                  |Clumps                        |clumps                        |9.0.0+11            |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.28.0_Forge_1.19.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.28.0              |COMMON_SET|Manifest: NOSIGNATURE
		JRFTL+[1.19]-1.4.1.jar                            |JRFTL                         |jrftl                         |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		citadel-1.12.12-1.19.jar                          |Citadel                       |citadel                       |1.12.12             |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.20.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
		configured-2.0.1-1.19.2.jar                       |Configured                    |configured                    |2.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		spawnermod-1.19.0-1.9.1+Forge.jar                 |Enhanced Mob Spawners         |spawnermod                    |1.9.1               |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.19.2-3.18.29.719.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19.2-3.18.29.719  |COMMON_SET|Manifest: NOSIGNATURE
		mcjtylib-1.19-7.0.3.jar                           |McJtyLib                      |mcjtylib                      |1.19-7.0.3          |COMMON_SET|Manifest: NOSIGNATURE
		rftoolsbase-1.19.1-4.0.3.jar                      |RFToolsBase                   |rftoolsbase                   |1.19.1-4.0.3        |COMMON_SET|Manifest: NOSIGNATURE
		forgivingvoid-forge-1.19-7.0.0.jar                |Forgiving Void                |forgivingvoid                 |7.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		balm-4.5.3.jar                                    |Balm                          |balm                          |4.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		rftoolspower-1.19-5.0.1.jar                       |RFToolsPower                  |rftoolspower                  |1.19-5.0.1          |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.1.33-universal.jar                |Forge                         |forge                         |43.1.33             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		ironchest-1.19.2-14.2.7.jar                       |Iron Chests                   |ironchest                     |1.19.2-14.2.7       |COMMON_SET|Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |COMMON_SET|Manifest: NOSIGNATURE
		swingthroughgrass-1.19-1.10.0.jar                 |SwingThroughGrass             |swingthroughgrass             |1.19-1.10.0         |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.19-2.23.jar                 |Mouse Tweaks                  |mousetweaks                   |2.23                |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.19.1-forge-8.3.0.jar                       |Jade                          |jade                          |8.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		appliedenergistics2-12.7.0.jar                    |Applied Energistics 2         |ae2                           |12.7.0              |COMMON_SET|Manifest: NOSIGNATURE
		AdLods-1.19.2-7.0.4.0-build.0599.jar              |Large Ore Deposits            |adlods                        |7.0.4.0             |COMMON_SET|Manifest: NOSIGNATURE
		Craftable+Saddles+[1.19+All]-1.4.jar              |Craftable Saddles             |craftable_saddles             |1.4                 |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.1.0.jar                   |Curios API                    |curios                        |1.19.2-5.1.1.0      |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.7-8.jar                 |Flywheel                      |flywheel                      |0.6.7-8             |COMMON_SET|Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.f.jar                         |Create                        |create                        |0.5.0.f             |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.19.2-76.jar                           |Patchouli                     |patchouli                     |1.19.2-76           |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_22.15.1_Forge_1.19.1.jar           |Xaero's Minimap               |xaerominimap                  |22.15.1             |COMMON_SET|Manifest: NOSIGNATURE
		gravestone-1.19.2-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.19.2-1.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		modonomicon-1.19.2-1.4.0.jar                      |Modonomicon                   |modonomicon                   |1.19.2-1.4.0        |COMMON_SET|Manifest: NOSIGNATURE
		constructionwand-1.19.1-2.8.jar                   |Construction Wand             |constructionwand              |1.19.1-2.8          |COMMON_SET|Manifest: NOSIGNATURE
		architectury-6.2.46-forge.jar                     |Architectury                  |architectury                  |6.2.46              |COMMON_SET|Manifest: NOSIGNATURE
		BambooEverything-forge-2.2.1-build.27+mc1.19.2.jar|Bamboo Everything             |bambooeverything              |2.2.1-build.27+mc1.1|COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |COMMON_SET|Manifest: NOSIGNATURE
		occultism-1.19.2-1.45.4.jar                       |Occultism                     |occultism                     |1.19.2-1.45.4       |COMMON_SET|Manifest: NOSIGNATURE
		FallingTree-1.19.2-3.10.0.jar                     |FallingTree                   |fallingtree                   |3.10.0              |COMMON_SET|Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		FastLeafDecay-30.jar                              |FastLeafDecay                 |fastleafdecay                 |30                  |COMMON_SET|Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.19.2-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.19.2-v1a          |COMMON_SET|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		CodeChickenLib-1.19.2-4.3.0.470-universal.jar     |CodeChicken Lib               |codechickenlib                |4.3.0.470           |COMMON_SET|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		EnderStorage-1.19.2-2.10.1.181-universal.jar      |EnderStorage                  |enderstorage                  |2.10.1.181          |COMMON_SET|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		geckolib-forge-1.19-3.1.22.jar                    |GeckoLib                      |geckolib3                     |3.1.22              |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: e5b91261-99c8-464b-bcd9-f398d776f946
	Flywheel Backend: GL33 Instanced Arrays
	FML: 43.1
	Forge: net.minecraftforge:43.1.33

**Comment by IminhaK** [comment]
The mod is not updated for Minecraft 1.19.2. Pushing an update soon
